/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApplication;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import spark.ModelAndView;
import spark.Request;
import spark.Response;
import spark.Route;
import spark.template.mustache.MustacheTemplateEngine;
import static spark.Spark.get;
import static spark.Spark.post;
import static spark.Spark.port;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    
    public static int search(ArrayList<Integer> array,int item,int lowerBound,int highBound){
        if (item>=lowerBound && item<=highBound){
            int count = 0;
            for (int i=0;i<array.size();i++){
                if (        array.get(i) == item){
                    count++;
                }
            }
            return count;
        }
         return 0;  
    } 


    public static void main(String[] args) {

        
        
        get("/", (req,res) -> "Hello, World!"); 

        get("/compute",
            (rq,rs) -> {
                Map<String,String> map = new HashMap<String,String>();
                map.put("In the first form","enter a list of integers seperated by a newline character.");
                map.put("In the second form", "enter another integer.");
                map.put("See how many times this whole number appears", "in the given list as a result.");
                map.put("result", "not computed yet!");
                return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine()
        );

        post("/compute",(req,res) -> {
            
            String input1 = req.queryParams("input1");
            java.util.Scanner sc1 = new java.util.Scanner(input1);
            sc1.useDelimiter("[;\r\n]+");
            java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
            while (sc1.hasNext()){
                int value = Integer.parseInt(sc1.next().replaceAll("\\s",""));
                inputList.add(value);
            }
            sc1.close();
            System.out.println(inputList); 

            String input2 = req.queryParams("input2").replaceAll("\\s","");
            int input2AsInt = Integer.parseInt(input2); 
            
            String input3 = req.queryParams("input3").replaceAll("\\s","");
            int input3AsInt = Integer.parseInt(input3); 
            
            String input4 = req.queryParams("input4").replaceAll("\\s","");
            int input4AsInt = Integer.parseInt(input4); 
            
            int result = App.search(inputList,input2AsInt,input3AsInt,input4AsInt); 
            Map<String,Integer> map = new HashMap<String,Integer>();
            map.put("result",result);

            return new ModelAndView(map,"compute.mustache");
        },
        new MustacheTemplateEngine()
        );
   
    }

    static int getHerokuAssignedPort() {

        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {

            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 4567; //return default port if heroku-port isn't set (i.e. on localhost)
    }    

}
