/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApplication;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void doesNotInclude(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);
        array.add(3);
        array.add(5);
        assertEquals(0,a.search(array, 2,-1,100) );
    }

    @Test void includeJustOne(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);
        array.add(2);
        array.add(5);
        assertEquals(1,a.search(array, 2,-1,97) );
    }

    @Test void moreThanOne(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);
        array.add(2);
        array.add(5);
        array.add(2);
        array.add(2);
        assertEquals(3,a.search(array, 2,-10,100) );
    }

    @Test void allOfTheElementsInArrayIsItem(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(2);
        array.add(2);
        array.add(2);
        array.add(2);
        array.add(2);
        assertEquals(array.size(),a.search(array, 2,-10,100) );
    }

    @Test void lowerThanLowerBound(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(2);
        array.add(5);
        array.add(2);
        array.add(2);
        array.add(3);
        array.add(1);
        assertEquals(0,a.search(array, 2,3,5));
    }
    @Test void higherThanHighBound(){
        App a = new App();
        ArrayList<Integer> array = new ArrayList<>();
        array.add(2);
        array.add(5);
        array.add(2);
        array.add(2);
        array.add(3);
        array.add(10);
        array.add(34);
        assertEquals(0,a.search(array, 10,3,5));
    }
}
